enable-magisk-update = true

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/AbakNacchan/revanced-extended/blob/revanced-extended/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
app-name = "YouTube"
build-mode = "module"
included-patches = "'Add splash animation' 'MaterialYou' 'Remove player controls background' 'Enable slide to seek'"
excluded-patches = "'Custom branding name YouTube' 'Announcements' 'Enable debugging' 'Change player flyout panel toggles'"
#version = "19.11.43"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
arch = "arm64-v8a"
apkmirror-arch = "arm64-v8a"

[Tiktok]
apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
build-mode = "module"

[Twitch]
apkmirror-dlurl = "https://apkmirror.com/apk/twitch-interactive-inc/twitch/"
build-mode = "module"
