enable-magisk-update = true

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/AbakNacchan/revanced-extended/blob/revanced-extended/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
app-name = "YouTube"
build-mode = "module"
included-patches = "'Add splash animation' 'MaterialYou' 'Remove player controls background' 'Enable slide to seek'"
excluded-patches = "'Custom branding name YouTube' 'Announcements' 'Enable debugging' 'Change player flyout panel toggles'"
version = "19.11.43"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
arch = "arm64-v8a"
apkmirror-arch = "arm64-v8a"

[Music]
enabled = false
build-mode = "both"
version = "latest"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
apkmirror-arch = "arm64-v8a"
included-patches = "'Permanent shuffle' 'Permanent repeat'"
excluded-patches = "'Custom branding name YouTube Music'"


[YouTube-Extended]
enabled = true
app-name = "Youtube Extended"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
cli-source = "anddea/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "module"
#archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"


