enable-magisk-update = true
patches-version = "v2.223.0-dev.19"
integrations-version = "v0.150.0-dev.4"

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/AbakNacchan/revanced-extended/blob/revanced-extended/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube Beta]
app-name = "YouTube"
build-mode = "both"
included-patches = "'Add splash animation' 'MaterialYou' 'Remove player controls background' 'Enable slide to seek' 'Custom branding icon YouTube'"
excluded-patches = "'Custom branding name YouTube' 'Announcements' 'Enable debugging' 'Change player flyout panel toggles'"
version = "19.11.43"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
apkmirror-arch = "arm64-v8a"
arch = "arm64-v8a"

[Music]
# enabled = false
build-mode = "both"
version = "latest"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
apkmirror-arch = "arm64-v8a"
included-patches = "'Permanent shuffle' 'Permanent repeat'"
excluded-patches = "'Custom branding name YouTube Music'"
